set nocompatible    "be iMproved, required
filetype off        "required

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'Lokaltog/vim-powerline'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'tacahiroy/ctrlp-funky'
Plugin 'scrooloose/nerdcommenter'
Plugin 'Shougo/neocomplcache.vim'
Plugin 'mattn/emmet-vim'
Plugin 'xml.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-scripts/taglist.vim'
Plugin 'ctags.vim'
"Plugin 'brookhong/cscope.vim'
Plugin 'sickill/vim-monokai'
Plugin 'vim-clang-format'
call vundle#end()

filetype plugin indent on

map <F3> :NERDTreeToggle<CR>
autocmd bufenter *
            \ if (winnr("$") == 1 && exists("b:NERDTree") && 
            \ b:NERDTree.isTabTree()) | q |
            \ endif
let NERDTreeShowHidden = 1

"let g:ctrlp_map = '<c-p>'
"let g:ctrlp_cmd = 'CtrlP'
map <F4> :CtrlPMixed<CR>
map <F5> :CtrlPMRU<CR>
let g:ctrlp_working_path_mode = '0'
let g:ctrlp_custom_ignore = {
    \ 'dir':    '\v[\/]\.(git|svn)$',
    \ 'file':   '\v\.(exe|so|dll|zip|tar|tar.gz|pyc|o)$',
    \ }
"默认使用全路径搜索，置1后按文件名搜索，准确率会有所提高，可以用<C-d>进行切换
let g:ctrlp_by_filename = 1
"默认不使用正则表达式，置1改为默认使用正则表达式，可以用<C-r>进行切换
let g:ctrlp_regexp = 1
"ctrlp的窗口显示在Vim窗口的底端(bottom) 模糊搜索结果按从上到下(ttb, top to
"bottom)的顺序显示 高度最小为1行，最大为20行，搜索结果最多显示20行
let g:ctrlp_match_window = 'bottom,order:btt,min:1,max:20,results:20'
let g:ctrlp_mruf_max=500
let g:ctrlp_follow_symlinks=1

map <F6> :CtrlPFunky<cr>
let g:ctrlp_extensions = ['funky']
let g:ctrlp_funky_syntax_highlight = 1

map <F7> :Tlist<cr>
let Tlist_Ctags_Cmd = 'ctags'
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_Use_Right_Window = 1
let Tlist_GainFocus_On_ToggleOpen = 1

let g:clang_format#auto_format_on_insert_leave = 1

set foldmethod=syntax
set foldlevelstart=99

set ruler
set showcmd
set showmode
set scrolloff=7
"set nowrap
set showmatch

set hlsearch
set incsearch
set ignorecase
set smartcase

set smartindent
set autoindent

set completeopt=longest,menu

set wildmenu
set wildignore=*.o,*~,*.pyc,*.class
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
inoremap <expr> <CR>    pumvisible() ? "\<C-y>" : "\<CR>"

if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

set relativenumber number
au FocusLost * :set norelativenumber number
au FocusGained * :set relativenumber
autocmd InsertEnter * :set norelativenumber number
autocmd InsertLeave * :set relativenumber
function! NumberToggle()
    if(&relativenumber == 1)
        set norelativenumber number
    else
        set relativenumber
    endif
endfunc
nnoremap <C-n> :call NumberToggle()<CR>

function! HideNumber()
    if(&relativenumber == &number)
        set relativenumber! number!
    elseif(&number)
        set number!
    else
        set relativenumber!
    endif
    set number?
endfunc
nnoremap <F2> :call HideNumber()<CR>

au InsertLeave * set nopaste
function! XTermPasteBegin()
    "set pastetoggle=<Esc>[201~
    set paste
    return ""
endfunc
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

set nobackup
set noundofile
set noswapfile
set nu
set mouse-=a
syntax on
colorscheme monokai
set backspace=indent,eol,start

set ts=4
set shiftwidth=4
set softtabstop=4
set expandtab

autocmd FileType python set cc=140
autocmd FileType python match Underlined /\%>139v.*/
"autocmd FileType python set tabstop=4 shiftwidth=4 expandtab ai
"autocmd FileType ruby,javascript,html,ccs,xml set tabstop=2 shiftwidth=2 softtabstop=2 expandtab ai"autocmd BufRead,BufNewFile *.md,*.mkd,*.markdown set filetype=markdown.mkd
"autocmd BufRead,BufNewFile *.part set filetype=html
"autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html.javascript tabstop=2 shiftwidth=2 softtabstop=2 expandtab ai

function! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfunc
autocmd FileType c,cpp,java,go,php,javascript,puppet,python,rust,twig,xml,yml,perl,sh,ttcn3 autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()
